{{- if .Values.monitoring.podLogs.enabled | default false -}}
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: {{ include "project.fullname" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ .Release.Namespace }}
  relabelings:
  - action: replace
    replacement: giantswarm
    targetLabel: giantswarm_observability_tenant
  selector:
    matchLabels:
      {{- include "project.selectorLabels" . | nindent 6 }}
{{- end -}}
