description = "Ubuntu 22.04 Jammy Jellyfish base image with buildpacks for Python with mysqlclient and Procfile"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/procfile:5.10.1"
version = "5.10.1"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/python:2.22.2"
version = "2.22.2"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/web-servers:0.27.2"
version = "0.27.2"

[lifecycle]
version = "0.20.4"

[[order]]

[[order.group]]
id = "paketo-buildpacks/web-servers"
version = "0.27.2"

[[order]]

[[order.group]]
id = "paketo-buildpacks/python"
version = "2.22.2"

[[order]]

[[order.group]]
id = "paketo-buildpacks/procfile"
version = "5.10.1"

[stack]
build-image = "python-mysql-jammy-builder:0.0.1"
id = "io.buildpacks.stacks.jammy"
run-image = "python-mysql-jammy-runner:0.0.1"
run-image-mirrors = []
