[_]
schema-version = "0.2"
id = "giantswarm.devplatform.python-service.{{ .ProjectName }}"
name = "python service built with CNBP pack"

[io.buildpacks]
builder = "paketobuildpacks/builder-jammy-base"

[[io.buildpacks.build.env]]
name = "BP_IMAGE_LABELS"
value = 'org.opencontainers.image.source=https://github.com/{{ .RepoOwner }}/{{ .ProjectName }}'

[[io.buildpacks.build.env]]
name = "BP_CPYTHON_VERSION"
value = "3.12.*"
