[_]
schema-version = "0.2"
id = "giantswarm.devplatform.go-service.{{ .ProjectName }}"
name = "go service built with CNBP pack"
version = "0.1.0"

[io.buildpacks]
builder = "paketobuildpacks/builder-jammy-tiny"

[[io.buildpacks.build.env]]
name = "BP_IMAGE_LABELS"
value = 'org.opencontainers.image.source=https://github.com/{{ .RepoOwner }}/{{ .ProjectName }}'

[[io.buildpacks.build.env]]
name = "BP_KEEP_FILES"
value = "templates/*:templates/"
