name: Pre-commit auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"

jobs:
  pre-commit-auto-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: 3.11
      - name: Install pre-commit
        run: pip install -U pre-commit
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          branch: update/pre-commit-autoupdate
          title: "[Bot] auto-update pre-commit hooks"
          commit-message: Auto-update pre-commit hooks
          author: Bot <bot@users.noreply.github.com>
          committer: Bot <bot@users.noreply.github.com>
          body: |
            Updates versions of tools in pre-commit configs to latest version.
          labels: dependencies, bot, pre-commit
