name: Trigger Root PR status check

on:
  pull_request:
    types: [closed]

jobs:
  trigger-root-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Trigger root PR workflow
        uses: actions/github-script@v7
        with:
          script: |
            const subPrNumber = context.payload.pull_request.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            // Search for the root PR that references the sub-PR
            const { data: issues } = await github.rest.search.issuesAndPullRequests({
              q: `repo:${repoOwner}/${repoName} type:pr in:comments ${subPrNumber}`,
            });

            if (issues.items.length === 0) {
              console.log("Root PR not found");
              return;
            }

            console.log(issues.items[0])
            const rootPrNumber = issues.items[0].number;

            // Get the root PR details to fetch the branch name
            const { data: rootPr } = await github.rest.pulls.get({
              owner: repoOwner,
              repo: repoName,
              pull_number: rootPrNumber,
            });

            const branchName = rootPr.head.ref;
            console.log("Triggering for branch #${branchName}");

            // Trigger the workflow dispatch event for the root PR
            await github.rest.actions.createWorkflowDispatch({
              owner: repoOwner,
              repo: repoName,
              workflow_id: 'check-sub-pr-status.yaml',
              ref: branchName,
            });

            console.log(`Triggered workflow for Root PR #${rootPrNumber}`);
